---
driver:
  name: docker
  use_internal_docker_network: true
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 15
  data_bags_path: test/fixtures/data_bags
  chef_license: accept

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[frUser::default]
    attributes:
